### ISSUE TITLE
Return a `m (Map Text (Either DbError PlutusData))` from `Database.getDatumsByHashes`

### ISSUE THREAD

**Issue by ngua** [mlabs-haskell/ogmios-datum-cache#112]
Currently, `getDatumsByHashes` loses _all_ datums upon a single error. The signature should change to something like

```haskell
getDatumsByHashes ::
  (MonadIO m, MonadReader r m, Has Connection r) =>
  [Text] ->
  m (Map Text (Either DbError PlutusData))
```

(ideally, we would have a `DataHash` newtype as well instead of using `Text` everywhere)

And the implementation updated accordingly

Related: #109

**Comment by adamczykm** [comment]
Theres a type of error that is not related to pulling/decoding any datum in particular but rather to db connection problems, hence we'll probably need something more like: 
` m (Either DbError (Map Text (Either DbError PlutusData)))`

**Comment by Luis-omega** [comment]
What's the expected behavior about errors now that we have this option? 

Previously we only had 3 cases 
- `There was an error retrieving datums (DataBaseErrorsNotFound)`
- `We have some error while decoding some datum (DatabaseErrorDecodeError)`
- `None of the previous errors happens and we have 0 or more datums (Vector (DataHash, PlutusData)`. 

Now we have : 
- `There was an error retrieving datums (Left DataBaseErrorsNotFound)`
- `We got 0 or more datums from db and all are decoded (RIght (Map DataHash (Right  PlutusData)))`.
- `We got 0 or more datums from db and some of them have errors (but not all) (RIght (Map DataHash (Either DataBaseError  PlutusData)))`.
- `We got 0 or more datums from db and all of them have errors while decoding (RIght (Map DataHash (Left DataBaseError)))`.   

Cases 1,2,4 can be handled just as the previous cases, but what should we do in case 3? Do we try to re-request them in the hope those were corrupted? Do we try to get them from db again hoping some db error happened?  Do were report both the faulty and correct datums as part of the request? Do we omit the faulty ones and retrieve just the ones that are correct? 

Omitting the wrong datums is a consistent option with previous behavior and won't need more API changes.

Returning both failures and success would require also checking all the datum that was originally requested and adding them as `Not Found` error, and changes in the API (apart from the ones needed now).
